apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: demo
  name: demo 
---   
apiVersion: v1
kind: Service
metadata:
  name: demo
  namespace: demo
  labels:
    app: demo
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
    nodePort: 30007
  selector:
    app: demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: demo
  name: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo  
  template:
    metadata:
      labels:
        app: demo
        version: v2
    spec:
      containers:
      - name: myapp
        image: janakiramm/myapp:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80  